import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'en' | 'zh';

interface SettingsState {
  language: Language;
  apiKey: string;
  apiBaseUrl: string;
  defaultModel: string;
  setLanguage: (lang: Language) => void;
  setApiKey: (key: string) => void;
  setApiBaseUrl: (url: string) => void;
  setDefaultModel: (model: string) => void;
}

export const useSettingsStore = create<SettingsState>()(
  persist(
    (set) => ({
      language: 'zh', // 默认中文
      apiKey: '',
      apiBaseUrl: 'https://api.openai.com/v1',
      defaultModel: 'gpt-3.5-turbo',
      setLanguage: (language) => set({ language }),
      setApiKey: (apiKey) => set({ apiKey }),
      setApiBaseUrl: (apiBaseUrl) => set({ apiBaseUrl }),
      setDefaultModel: (defaultModel) => set({ defaultModel }),
    }),
    { name: 'prompt-grid-settings' }
  )
);

export const i18n = {
  en: {
    allPrompts: 'All Prompts',
    favorites: 'Favorites',
    folders: 'Folders',
    searchCommands: 'Search commands...',
    prompts: 'Prompts',
    filter: 'Filter...',
    noPrompts: 'No prompts found.',
    untitled: 'Untitled Prompt',
    emptyPrompt: 'Empty prompt...',
    selectPrompt: 'Select a prompt or press ⌘K to search',
    promptTitle: 'Prompt Title',
    writePrompt: 'Write your prompt here... Use {{variable}} to create dynamic inputs.',
    playground: 'Playground',
    variables: 'Variables',
    noVariables: 'No variables detected. Use {{name}} syntax.',
    runTest: 'Run Test',
    unconfigured: '(Not Configured)',
    copyPrompt: 'Copy Filled Prompt',
    newFolder: 'New folder...',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    // Command Palette
    searchPlaceholder: 'Search prompts or commands...',
    noResults: 'No results found.',
    actions: 'Actions',
    createPromptAction: 'Create New Prompt',
    createFolderAction: 'Create New Folder',
    switchThemeAction: 'Switch Theme',
    switchLangAction: 'Switch Language',
    copySuccess: 'Copied to clipboard!',
    // Phase 2
    tags: 'Tags',
    allTags: 'All Tags',
    addTagPlaceholder: 'Add tag and press Enter...',
    moveFolder: 'Move to Folder...',
    exportSuccess: 'Data exported successfully!',
    noFolder: 'No Folder',
    // API Settings
    apiConfig: 'API Configuration',
    apiKey: 'API Key',
    apiBaseUrl: 'Base URL',
    defaultModel: 'Default Model',
    saveSettings: 'Save Settings',
    testResult: 'Test Result',
    testing: 'Testing...',
    testError: 'Test Error',
    modelOverride: 'Override Model',
    temperature: 'Temperature',
    // Phase 4
    systemInstructions: 'System Instructions',
    systemInstructionsPlaceholder: 'Enter system instructions here (e.g. "You are an expert assistant...")',
    saveTestCase: 'Save',
    loadTestCase: '-- Load Test Case --',
    copyText: 'Text',
    copyJson: 'JSON',
    copied: 'Copied!',
    optimizePrompt: '✨ Optimize',
    optimizing: 'Optimizing...',
    applyOptimization: 'Apply to Editor',
    optimizationTitle: 'AI Prompt Optimizer',
    optimizationDesc: 'Let the AI rewrite your prompt using expert prompt engineering best practices.',
    dataManagement: 'Data Management',
    exportData: 'Export Backup',
    importData: 'Import Backup',
    importSuccess: 'Data imported successfully!',
    importError: 'Invalid backup file.',
    importMode: 'Import Mode',
    importMerge: 'Merge with existing data',
    importReplace: 'Replace all current data',
    importMergeHint: 'Merge keeps current items and updates duplicates with the same ID.',
    confirmImportMerge: 'Import this backup and merge it with existing data?',
    confirmImportReplace: 'Replace all current prompts and folders with this backup? This cannot be undone.',
    confirmDeletePrompt: 'Delete this prompt? This cannot be undone.',
    confirmDeleteFolder: 'Delete this folder? Prompts inside it will be moved to No Folder.',
    apiKeyMissing: 'Please configure your API Key in Settings first.',
    modelName: 'Model Name',
    testCaseName: 'Test case name',
    testCaseNamePlaceholder: 'e.g. Formal Tone',
    saveTestCaseValues: 'Save current values',
    toggleTheme: 'Toggle theme',
    toggleLanguage: 'Toggle language',
    downloadDesktopApp: 'Download Desktop App',
    readyToOptimize: 'Ready to optimize',
    startOptimization: 'Start optimization',
    optimizationReadyDesc: 'Send the current draft to the configured model and review the optimized version before applying it.',
    optimizationComplete: 'Optimization complete',
    cancel: 'Cancel',
  },
  zh: {
    allPrompts: '所有提示词',
    favorites: '我的收藏',
    folders: '文件夹',
    searchCommands: '全局搜索 / 快捷指令',
    prompts: '提示词列表',
    filter: '过滤查找...',
    noPrompts: '暂无提示词。',
    untitled: '未命名提示词',
    emptyPrompt: '空白提示词...',
    selectPrompt: '请在列表中选择一个提示词，或按 ⌘K 搜索',
    promptTitle: '提示词标题',
    writePrompt: '在此输入你的提示词... 使用 {{变量名}} 来创建动态填空。',
    playground: '测试沙盒',
    variables: '动态变量',
    noVariables: '未检测到变量。请使用 {{name}} 语法。',
    runTest: '测试运行',
    unconfigured: '(未配置 API)',
    copyPrompt: '一键复制最终结果',
    newFolder: '新建文件夹...',
    settings: '偏好设置',
    theme: '外观主题',
    language: '显示语言',
    light: '浅色模式',
    dark: '深色模式',
    // Command Palette
    searchPlaceholder: '搜索提示词或快捷指令...',
    noResults: '未找到任何结果。',
    actions: '快捷操作',
    createPromptAction: '新建提示词',
    createFolderAction: '新建文件夹',
    switchThemeAction: '切换外观主题',
    switchLangAction: '切换显示语言',
    copySuccess: '已复制到剪贴板！',
    // Phase 2
    tags: '标签',
    allTags: '全部标签',
    addTagPlaceholder: '输入标签后按回车添加...',
    moveFolder: '移动到文件夹...',
    exportSuccess: '数据导出成功！',
    noFolder: '未分类',
    // API Settings
    apiConfig: 'API 接口配置',
    apiKey: 'API 密钥 (API Key)',
    apiBaseUrl: '接口地址 (Base URL)',
    defaultModel: '默认模型',
    saveSettings: '保存设置',
    testResult: '测试结果',
    testing: '正在请求...',
    testError: '测试发生错误',
    modelOverride: '模型配置',
    temperature: '随机性 (Temperature)',
    // Phase 4
    systemInstructions: '系统提示词 (System Instructions)',
    systemInstructionsPlaceholder: '在此输入系统设定（如："你是一个人工智能助手..."）',
    saveTestCase: '保存用例',
    loadTestCase: '-- 载入测试用例 --',
    copyText: '纯文本',
    copyJson: 'JSON',
    copied: '已复制！',
    optimizePrompt: '✨ AI 优化',
    optimizing: '正在施展魔法...',
    applyOptimization: '应用到编辑器',
    optimizationTitle: 'AI 提示词优化引擎',
    optimizationDesc: '让大模型利用专业的提示词工程最佳实践，自动为您重写、扩充、优化这组提示词。',
    dataManagement: '数据管理',
    exportData: '导出备份',
    importData: '导入备份',
    importSuccess: '数据导入成功！',
    importError: '无效的备份文件。',
    importMode: '导入方式',
    importMerge: '合并到当前数据',
    importReplace: '替换全部当前数据',
    importMergeHint: '合并会保留现有内容，并用备份中相同 ID 的项目更新旧项目。',
    confirmImportMerge: '确定要导入这个备份并与当前数据合并吗？',
    confirmImportReplace: '确定要用这个备份替换全部当前提示词和文件夹吗？此操作不可撤销。',
    confirmDeletePrompt: '确定删除这个提示词吗？此操作不可撤销。',
    confirmDeleteFolder: '确定删除这个文件夹吗？其中的提示词会移动到未分类。',
    apiKeyMissing: '请先在偏好设置中配置 API Key。',
    modelName: '模型名称',
    testCaseName: '测试用例名称',
    testCaseNamePlaceholder: '例如：正式语气',
    saveTestCaseValues: '保存当前变量',
    toggleTheme: '切换主题',
    toggleLanguage: '切换语言',
    downloadDesktopApp: '下载桌面版',
    readyToOptimize: '准备优化',
    startOptimization: '开始优化',
    optimizationReadyDesc: '将当前草稿发送给已配置的模型，应用前可先查看优化结果。',
    optimizationComplete: '优化完成',
    cancel: '取消',
  }
};
